name: 'PR Reminder'
description: 'PR Reminder'
author: 'SeongHo5'
inputs:
  repo-token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: false
  platform:
    description: '리마인드를 보낼 플랫폼(slack | discord)'
    required: true
  webhook-url:
    description: '생성한 Webhook URL'
    required: true
  remind-time:
    description: '리마인드를 보낼 기준 시간, PR이 이 시간 이상 대기했다면 리마인드를 보냅니다!'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: gray-dark
  icon: 'aperture'
